name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: git clone https://github.com/${{ github.repository }}.git .

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan gh-pages
          git rm -rf .
          cp ../index.html .  # Ensure index.html is in the root directory
          git add index.html
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages
